trigger:
  branches:
    include:
      - master

pool: Adrian-PC

steps:
- task: GoTool@0
  inputs:
    version: '1.21.7'
    
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- script: |
    go mod download
  displayName: 'Download dependencies'

- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '''$(Build.ArtifactStagingDirectory)/go_cards_server/cmd'''