trigger:
  branches:
    include:
      - master

pool: Adrian-PC

steps:
- script: |
    echo "##[debug] System Default Working Directory: $(System.DefaultWorkingDirectory)"
    echo "##[debug] Build Artifact Staging Directory: $(Build.ArtifactStagingDirectory)"
    dir
- task: GoTool@0
  inputs:
    version: '1.13.5'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)/go_cards_server'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/go_cards_server'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop