trigger:
  branches:
    include:
      - main

pool: Adrian-PC

steps:
- script: |
    echo "##[debug] System Default Working Directory: $(System.DefaultWorkingDirectory)"
    echo "##[debug] Build Artifact Staging Directory: $(Build.ArtifactStagingDirectory)"
    dir
- task: GoTool@0
  inputs:
    version: '1.21.7'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)/go_cards_server/cmd'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/go_cards_server/cmd'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop
- task: Docker@2
  inputs:
    containerRegistry: 'GoCheatACRServiceConnectionServicePrincipal'
    repository: 'gocheatserver'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildId)'
- task: AzureContainerApps@1
  inputs:
    azureSubscription: 'GoCheatServiceConnection'
    containerAppName: 'gocheatservercontainerapp'
    resourceGroup: 'GoCheat'
    containerAppEnvironment: 'gocheat-env'
    imageToDeploy: 'gocheatregistry.azurecr.io/gocheatserver:$(Build.BuildId)'
    acrName: 'gocheatregistry'
    acrUsername: 'GoCheatRegistry'
    acrPassword: $(acrPassword)
    targetPort: '8080'
    environmentVariables: REACT_APP_DOMAIN=https://gocheat.win